services:
  - type: web
    name: snapmaker-u1-studio-backend
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: frankfurt
    healthCheckPath: /api/health
    envVars:
      - key: PORT
        value: 8000
      - key: ALLOWED_ORIGINS
        value: "*"
